version: "3.2"
services:
  kafka:
    image: afriedrichsen/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.86.32
      KAFKA_ZOOKEEPER_CONNECT: 192.168.86.57:2181
      KAFKA_CREATE_TOPICS: "LogProcessing:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloudera-webnet
  harvester:
    build:
      context: ./app/feed/harvest
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
    # For simple demonstration, this is our "landing zone" for log files.
      - /Users/adf/drop:/app/data/input
    networks:
      - cloudera-webnet

networks:
  cloudera-webnet:
